#!/bin/sh

export XDG_DATA_DIRS="$HOME/.local/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

[ -r "$HOME/.config/sway/scripts/session-env" ] && . "$HOME/.config/sway/scripts/session-env"

exec rofi \
    -show drun \
    -show-icons \
    -icon-theme Papirus-Dark \
    -matching fuzzy \
    -sorting-method fzf \
    -sort \
    -drun-use-desktop-cache \
    -drun-reload-desktop-cache \
    -drun-match-fields "name,generic,keywords,categories,comment,exec" \
    -drun-display-format "{name}" \
    -application-fallback-icon application-x-executable \
    -terminal foot \
    -display-drun "Apps" \
    -prompt "Launch"
