[ColorEffects:Disabled]
Color=102,102,102
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=0

[ColorEffects:Inactive]
ChangeSelectionColor=false
Color=102,102,102
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=true
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=5,5,5
BackgroundNormal=0,0,0
DecorationFocus=74,74,74
DecorationHover=42,42,42
ForegroundActive=230,230,230
ForegroundInactive=102,102,102
ForegroundLink=154,154,154
ForegroundNegative=255,255,255
ForegroundNeutral=154,154,154
ForegroundNormal=230,230,230
ForegroundPositive=200,200,200
ForegroundVisited=154,154,154

[Colors:Selection]
BackgroundAlternate=42,42,42
BackgroundNormal=42,42,42
DecorationFocus=74,74,74
DecorationHover=42,42,42
ForegroundActive=230,230,230
ForegroundInactive=154,154,154
ForegroundLink=230,230,230
ForegroundNegative=255,255,255
ForegroundNeutral=154,154,154
ForegroundNormal=255,255,255
ForegroundPositive=200,200,200
ForegroundVisited=154,154,154

[Colors:Tooltip]
BackgroundAlternate=0,0,0
BackgroundNormal=0,0,0
DecorationFocus=74,74,74
DecorationHover=42,42,42
ForegroundActive=230,230,230
ForegroundInactive=102,102,102
ForegroundLink=154,154,154
ForegroundNegative=255,255,255
ForegroundNeutral=154,154,154
ForegroundNormal=230,230,230
ForegroundPositive=200,200,200
ForegroundVisited=154,154,154

[Colors:View]
BackgroundAlternate=5,5,5
BackgroundNormal=0,0,0
DecorationFocus=74,74,74
DecorationHover=42,42,42
ForegroundActive=230,230,230
ForegroundInactive=102,102,102
ForegroundLink=154,154,154
ForegroundNegative=255,255,255
ForegroundNeutral=154,154,154
ForegroundNormal=230,230,230
ForegroundPositive=200,200,200
ForegroundVisited=154,154,154

[Colors:Window]
BackgroundAlternate=5,5,5
BackgroundNormal=0,0,0
DecorationFocus=74,74,74
DecorationHover=42,42,42
ForegroundActive=230,230,230
ForegroundInactive=102,102,102
ForegroundLink=154,154,154
ForegroundNegative=255,255,255
ForegroundNeutral=154,154,154
ForegroundNormal=230,230,230
ForegroundPositive=200,200,200
ForegroundVisited=154,154,154

[General]
ColorScheme=GruvboxNeutral
Name=GruvboxNeutral
shadeSortColumn=true

[KDE]
contrast=0

[WM]
activeBackground=0,0,0
activeBlend=0,0,0
activeForeground=230,230,230
inactiveBackground=5,5,5
inactiveBlend=5,5,5
inactiveForeground=102,102,102
